[boris]
  version = 1

[build.dist-7-10]

[build.branches-7-10]

[build.cabal-test-7-10]

[build.cabal-test-branches-7-10]

[build.dist-8-0]

[build.branches-8-0]

[build.cabal-test-8-0]

[build.cabal-test-branches-8-0]

[build.submodules]
  command = [["dangling-refs"]]

[build.submodules-branches]
  command = [["dangling-refs"]]

[build.validate]
  pre = []
  command = [["validate-respect"]]
  success = []
